version: "3.9"  
  
services:  
  db:
    image: postgres:16-alpine
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: smartbiz
      POSTGRES_PASSWORD: Smartbiz123!
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:  
      - my-net
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: asanov.personal@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Smartbiz123!
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:  
      - my-net

volumes:
  local_pgdata:
  pgadmin-data:

networks:  
  my-net:  
    external: true